### ISSUE TITLE
Test failures under perl 5.24.0

### ISSUE THREAD

**Issue by DrHyde** [tobyink/p5-lexical-underscore#3]
Can't use global $_ in "my" at t/01basic.t line 12, near "my $_ "
Can't use global $_ in "my" at t/01basic.t line 23, near "my $_ "
Can't use global $_ in "my" at t/01basic.t line 28, near "my $_ "

This breaks Scalar::Does, Data::Domain, Params::Validate::Dependencies (which is where I noticed this) and everything else that might depend on them.

**Comment by tobyink** [comment]
Fixed in 0.004
http://matrix.cpantesters.org/?dist=lexical-underscore+0.004

**Comment by DrHyde** [comment]
Thanks!
